#!/bin/bash
#-------------------------------------------------------------------------------

Collect the data from AWS

#-------------------------------------------------------------------------------
# https://melb-datathon.s3.ap-southeast-2.amazonaws.com/index.html

ws s3 cp s3://melb-datathon/SAMPLE [destination] --recursive

#-------------------------------------------------------------------------------
# for u in $(cat url) ; do
#   cd /short/dx2/gay548/MelbourneDatathon2018/${u%/*}
#   pwd
#   wget https://melb-datathon.s3.ap-southeast-2.amazonaws.com/${u}
# done
# 
#-------------------------------------------------------------------------------
